version: "3"
services:
  app:
    build:
      context: "."
      args:
        - ORIGIN=http://127.0.0.1:8080
        - NODE_ENV=DEVELOPMENT
    container_name: app
    environment:
      - TZ=Europe/Amsterdam
      - DEBUG=TRUE
    ports:
      - 8080:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"